### ISSUE TITLE
It's trying to verify the recipient?

### ISSUE THREAD

**Issue by sweepyoface** [daniel-zahariev/php-aws-ses#35]
Getting this error on the email address in the $m->addTo() field.

PHP Warning:  SimpleEmailService::sendEmail(): Sender - MessageRejected: Email address is not verified. The following identities failed the check in region US-E     AST-1: example@example.com
Request Id: 831409ab-8b58-xxxx-a8ad-111a7885df63

`require 'SimpleEmailService.php';
require 'SimpleEmailServiceRequest.php';
require 'SimpleEmailServiceMessage.php';

$m = new SimpleEmailServiceMessage();
$m->addTo('example@example.org');
$m->setFrom('me@me.me');
$m->setSubject('Hello, world!');
$m->setMessageFromString('This is the message body.');

$ses = new SimpleEmailService('XXX', 'XXX');
print_r($ses->sendEmail($m));`

**Comment by craig-winaust** [comment]
Looks like you are in the SES sandbox. It will reject unverified recipient email addresses.
You will have to add the sender email address to the verified list to continue testing. Otherwise, send to an address at your verified domain.
http://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-addresses-and-domains.html

To remove the restriction on recipient addresses and increase your sending limits, you need to open a case in Support Center by using the following instructions.
http://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html

**Comment by sweepyoface** [comment]
Thanks, I didn't realize that.
