### ISSUE TITLE
35 Process open FD table is full

### ISSUE THREAD

**Issue by dhavalsisodiya** [daniel-zahariev/php-aws-ses#45]
I am trying to send 2000+emails in the loop. Among them, 900+ emails are sent successfully. But after that I am getting below error:

SimpleEmailService::sendEmail(): 35 Process open FD table is full

So what should I do to fix this issue?

**Comment by user0250** [comment]
Do you fix it? I also met this question,causing the server to crash.
what should i do to fix this issue

**Comment by dhavalsisodiya** [comment]
No, the issue is not fixed yet.

**Comment by Eminov** [comment]
If you are using linux.
Increase the "Maximum number of open file descriptors", by default is 1024.
You can see the limits with command - "ulimit -a"
If you want to increase the limits, use "sudo ulimit -n 65536"

**Comment by dhavalsisodiya** [comment]
I have already tried that with setting the limit to 65K. But still,  it was not working. Do you know which function is writing the data in FD Table? I have checked the code and file_get_contents is used to get the content of the file.  file_get_contents is read a file and closes the file afterwards. So not sure why the FD table limit causing the issue.

I have also received the response from AWS Team:

"you are not closing the file descriptor after sending the mails. You need to close the file descriptor after the job is done. That way it wont exhaust the limit set on the number of FDs assigned."

**Comment by user0250** [comment]
do your system will stop  when met this error  ？I use laravel  ，it can be sent normally but read log have error。
Sent from Mail Master
On 09/26/2017 13:05, dhavalsisodiya wrote: I have already tried that with setting the limit to 65K. But still,  it was not working. Do you know which function is writing the data in FD Table? I have checked the code and file_get_contents is used to get the content of the file.  file_get_contents is read a file and closes the file afterwards. So not sure why the FD table limit causing the issue.
I have also received the response from AWS Team:
"you are not closing the file descriptor after sending the mails. You need to close the file descriptor after the job is done. That way it wont exhaust the limit set on the number of FDs assigned."

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/daniel-zahariev/php-aws-ses","title":"daniel-zahariev/php-aws-ses","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/daniel-zahariev/php-aws-ses"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dhavalsisodiya in #45: I have already tried that with setting the limit to 65K. But still,  it was not working. Do you know which function is writing the data in FD Table? I have checked the code and file_get_contents is used to get the content of the file.  file_get_contents is read a file and closes the file afterwards. So not sure why the FD table limit causing the issue.\r\n\r\nI have also received the response from AWS Team:\r\n\r\n\"you are not closing the file descriptor after sending the mails. You need to close the file descriptor after the job is done. That way it wont exhaust the limit set on the number of FDs assigned.\""}],"action":{"name":"View Issue","url":"https://github.com/daniel-zahariev/php-aws-ses/issues/45#issuecomment-332087461"}}}

**Comment by dhavalsisodiya** [comment]
No doesn't stop after this error message. We have handled the exception so the system will try to send email to next email address which is in the queue.

**Comment by user0250** [comment]
The error isn’t library’s error.  It is operating system’s error , For example  . too much open files operating system display the error So you can read the achieve code
Sent from Mail Master
On 09/26/2017 16:26, dhavalsisodiya wrote: No doesn't stop after this error message. We have handled the exception so the system will try to send email to next email address which is in the queue.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/daniel-zahariev/php-aws-ses","title":"daniel-zahariev/php-aws-ses","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/daniel-zahariev/php-aws-ses"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dhavalsisodiya in #45: No doesn't stop after this error message. We have handled the exception so the system will try to send email to next email address which is in the queue."}],"action":{"name":"View Issue","url":"https://github.com/daniel-zahariev/php-aws-ses/issues/45#issuecomment-332125010"}}}

**Comment by user0250** [comment]
About send mails code 
Sent from Mail Master
On 09/26/2017 16:55, yuyong wrote: 
The error isn’t library’s error.  It is operating system’s error , For example  . too much open files operating system display the error So you can read the achieve code
Sent from Mail Master
On 09/26/2017 16:26, dhavalsisodiya wrote: No doesn't stop after this error message. We have handled the exception so the system will try to send email to next email address which is in the queue.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/daniel-zahariev/php-aws-ses","title":"daniel-zahariev/php-aws-ses","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/daniel-zahariev/php-aws-ses"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dhavalsisodiya in #45: No doesn't stop after this error message. We have handled the exception so the system will try to send email to next email address which is in the queue."}],"action":{"name":"View Issue","url":"https://github.com/daniel-zahariev/php-aws-ses/issues/45#issuecomment-332125010"}}}

**Comment by daniel-zahariev** [comment]
Please, refer to the [Sending Bulk message](https://github.com/daniel-zahariev/php-aws-ses#sending-bulk-messages) section in the documentation.

**Comment by 24bulut** [comment]
I had this error too. My resolve is in SimpleEmailServiceRequest file . You can add this code the end of getResponse() function => "curl_close($curl_handler);". If you use singleton, you must do this.
