### ISSUE TITLE
How to set custom header or tags to use with Amazon Cloud Watch and get real metrics.

### ISSUE THREAD

**Issue by osalas891123** [daniel-zahariev/php-aws-ses#49]
Need to set custom email headers or email tags to work together with Amazon Cloud Watch and sent events. Is this possible with the library

**Comment by jdrydn** [comment]
@daniel-zahariev Wondering this too.

I'm trying to send emails via a configuration set, however I'm seeing inconsistent results. Some emails are sent through the dedicated IP and some emails are still sent through the shared IP pool.

I'm adding the relevant custom header as [per this documentation](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-configuration-sets-in-email.html):

```php
$ses = new SimpleEmailService(AWS_ACCESS_KEY, AWS_SECRET_KEY, SimpleEmailService::AWS_EU_WEST1, true);
$ses->enableVerifyPeer(false);
$ses->setBulkMode(true);
$message = new SimpleEmailServiceMessage();
// ...
$message->addCustomHeader('X-SES-CONFIGURATION-SET: ConfigSet');
$ses->sendEmail($m, true);
```

Adding the following debug line will prepend the headers to the top of the raw messages, as expected:

```php
print_r(base64_decode($message->getRawMessage()));
```
```txt
X-SES-CONFIGURATION-SET: ConfigSet
To:{{ removed }}
From: {{ removed }}
Subject: {{ removed }}
MIME-Version: 1.0
Content-type: Multipart/Mixed; boundary="..."
```

Unsure if there's a bug going on here or if I should revert to the standard AWS-SES SDK since my use-case now involves a configuration set? Any advice would be much appreciated!

**Comment by brod-ie** [comment]
Having the same issue

**Comment by daniel-zahariev** [comment]
Thanks everyone for reporting this. 
I've just added support for SES Configuration Set and Message Tags in the latest release (0.9.1).
While working on it i found that Configuration sets are not global but per region and until i realised this i was banging my head why is it saying that the configuration set is missing.

**Comment by jdrydn** [comment]
@daniel-zahariev Thanks for this. I can see you set `ConfigurationSetName` in the SES request, and I can see the relevant header being set in the `getRawMessage` method, but I'm still getting emails being sent through the shared IP pool. I've reached out to AWS to see if they can identify an incorrect setting with my SES setup & I'll update this thread with the outcome.
